export enum ConfigKey {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  GG_SEARCH_API_KEY = 'GG_SEARCH_API_KEY',
  GG_SEARCH_SO_CX = 'GG_SEARCH_SO_CX',
  GG_SEARCH_MDN_CX = 'GG_SEARCH_MDN_CX',
  GG_SEARCH_W3S_CX = 'GG_SEARCH_W3S_CX',
  SLACK_SIGN_IN_TOKEN = 'SLACK_SIGN_IN_TOKEN',
}
